### PR TITLE
Fix using deprecated functions.

### PR DESCRIPTION
**Pull request by hannupekka**
Fixes issue #4

### CODE REVIEW

**Comment by johanneslumpe** [comment]
Thanks! Will merge this and then publish a new major version to npm!

**Comment by johanneslumpe** [comment]
@hannupekka oh would you mind fixing the example as well so it works with the updated code?

**Comment by hannupekka** [comment]
@johanneslumpe should be fixed in fbf8bf0e63886aa94e70f41864f0a0d59e23f545

**Comment by hannupekka** [comment]
Oops, missed that :) Fixed in 08be1c046d00c63665bd3deb40b2a8c6cea742a1

**Comment by johanneslumpe** [comment]
Thanks!

**Pull request merged**
